### ISSUE TITLE
Can't install on latest Flutter version 

### ISSUE THREAD

**Issue by AlmogRnD** [codegrue/card_settings#156]
I'm getting the following error, is this supported to the latest version. 

Because card_settings >=1.9.4 depends on flutter_cupertino_settings ^0.3.1 which depends on cupertino_icons ^0.1.3, card_settings >=1.9.4 requires cupertino_icons ^0.1.3.

So, because giliw_mobile_app depends on both card_settings ^1.15.0 and cupertino_icons ^1.0.0, version solving failed.
pub get failed (1; So, because giliw_mobile_app depends on both card_settings ^1.15.0 and cupertino_icons ^1.0.0, version solving failed.)

**Comment by enricobenedos** [comment]
Try to add the dependency override for `flutter_cupertino_settings` on your `pubspec.yaml`. In this case you will use a specific commit of a forked repository in which `cupertino_icons` package has been updated.
```yaml
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  .... your packages

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dependency_overrides:
  flutter_cupertino_settings:
    git:
      url: https://github.com/jibiel/flutter_cupertino_settings.git
      ref: dfb575c82b67ff76d6df240ccda9fefb53596709
```
