### ISSUE TITLE
Null safety and Flutter 2.0 support

### ISSUE THREAD

**Issue by enricobenedos** [codegrue/card_settings#164]
Good morning,

it will be beautiful if this package can support Flutter 2.0 and null safety. It is also needed to update dependencies on order to achieve that.

Is there any planning about this new migration?

Thank you

**Comment by codegrue** [comment]
Working on it now

**Comment by codegrue** [comment]
Hey everyone. I cannot upgrade to 2.0 until the Cupertino package is updated. I am thinking about ripping this completely out for the 2.0 and having only Material. Any concerns?

**Comment by robertoltrocha** [comment]
Hi @codegrue 
I only use Material, if I can migrate or make a version only with the Material it will be welcome.
Many packages I cannot update because I depend on yours.
thanks

**Comment by codegrue** [comment]
Same. I've been restricted likewise by what this package depends on.

**Comment by codegrue** [comment]
I'm halfway through the nullsafety changes. There are over 1k lines to fix.. ugh.

**Comment by robertoltrocha** [comment]
I understand. Thank you for your commitment.

**Comment by enricobenedos** [comment]
I'm using only material on both iOS and Android. It is not a problem to remove Cupertino widget, even if it is a shame because I think a lot of work has been done to implement it in this package. When can try to fork the repo and create a version that support the null safety.

**Comment by codegrue** [comment]
I wanted to update everyone. I have completed migrating the code (over 1000 changes) and have it checked in locally. I need to do a full regression test before pushing it up. My goal is Friday so you can test, then to pub.dev if all is good. I branded the 1.x code so you can link to that if you still need to use the old version.

**Comment by codegrue** [comment]
I pushed the updated code up. There is still an issue with the currency field, but otherwise, I think everything is working. I will continue to test over the next few days,

**Comment by enricobenedos** [comment]
Hey @codegrue,
can you please support the latest `into 0.17.0` stable null safety version?
```
Because every version of card_settings from git depends on intl >=0.16.0 <=0.17.0-nullsafety.2 and every version of flutter_localizations from sdk depends on intl 0.17.0, card_settings from git is incompatible with flutter_localizations from sdk.
So, because wamii_app depends on both flutter_localizations any from sdk and card_settings from git, version solving failed.
```
Thanks

**Comment by codegrue** [comment]
It's coming soon. I have other dependencies that are preventing me from releasing up update. Until then you can override in your pubspec.yaml:

```
dependency_overrides:
    intl: ^0.17.0
```

**Comment by NTMS2017** [comment]
I have been using this plugin since version 1.3.1 and I thank you for that. I am waiting nullsafety version as well.

Currently updating my app to Flutter SDK 2. I update most of the plugin and  only waiting card_settings plugin.

Currently I am using following plugins in my app as shown below. When I check the plugin pub spec.yaml you update theintl version and plugin now uses intl: ^0.17.0. Which is good for me. But plugin still use flutter_cupertino_settings: ^0.3.1. Can you update this as well? If not should I have to change my cupertino_icons to version 1.0?


```
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.0.0-nullsafety.11
  auto_size_text: ^3.0.0-nullsafety.0
  connectivity: ^3.0.3
  flutter_spinkit: ^5.0.0
  package_info: ^2.0.0
  in_app_update: ^2.0.0
  upgrader: ^3.1.0
  provider: ^5.0.0
  encrypt: 2.1.0
  onesignal_flutter: ^2.6.3
  convex_bottom_bar: ^3.0.0
  sailor: ^0.7.1
  http: ^0.13.1
  dots_indicator: ^2.0.0
  intl: ^0.17.0
  popup_menu: ^1.0.5
  flutter_picker: ^2.0.0
  flutter_slidable: ^0.5.7
  flutter_datetime_picker: ^1.5.0
  mailer: ^4.0.0
  path_provider: ^2.0.1
  diacritic: ^0.1.3
  image: ^3.0.2
  flutter_speed_dial: ^3.0.5
```

**Comment by codegrue** [comment]
The nullsafe code is checked in if you reference the Github repository directly. This needs some testing before a full release. Currency is not working yet.

**Comment by NTMS2017** [comment]
I did but didnt work. I really need this to finish my app to upload App Store. :(


environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


```
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  intl: 0.17.0
  #card_settings: ^1.16.3
  card_settings:
    git:
      url: https://github.com/codegrue/card_settings.git
  font_awesome_flutter:
  adaptive_theme: ^2.0.0
  google_fonts: ^2.0.0
```

```
Because every version of card_settings from git depends on flutter_cupertino_settings ^0.3.1 which depends on cupertino_icons ^0.1.3, every version of card_settings from git requires cupertino_icons ^0.1.3.
So, because ntms_card163 depends on both cupertino_icons ^1.0.2 and card_settings from git, version solving failed.
pub get failed (1; So, because ntms_card163 depends on both cupertino_icons ^1.0.2 and card_settings from git, version solving failed.)
```

And when I try to override I got another error as: 
```
Because ntms_card163 depends on cupertino_icons ^0.3.1 which doesn't match any versions, version solving failed.
pub get failed (1; Because ntms_card163 depends on cupertino_icons ^0.3.1 which doesn't match any versions, version solving failed.)
```

**Comment by NTMS2017** [comment]
OK, This looks work but didnt test yet.

```
  #cupertino_icons: ^1.0.2
  intl: ^0.17.0
  #card_settings: ^1.16.3
  card_settings:
    git:
      url: https://github.com/codegrue/card_settings.git
  font_awesome_flutter:
  adaptive_theme: ^2.0.0
  google_fonts: ^2.0.0
```
